os: Ubuntu2204

services:
- docker

#for testing purposes only
build_script:
  - dotnet build test/Renci.SshNet.IntegrationTests/

test_script:
- mkdir artifacts
- dotnet test --no-restore --no-build --results-directory artifacts --logger console;verbosity=detailed --logger liquid.md;LogFileName=TestReport.md -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput=artifacts/coverage.xml test/Renci.SshNet.IntegrationTests/Renci.SshNet.IntegrationTests.csproj
- ls artifacts
  
