os: Ubuntu2204

#for testing purposes only
build_script:
  - dotnet build test/Renci.SshNet.IntegrationTests/

test_script:
- mkdir artifacts
- docker build -t sshtest --no-cache -f ./test/Renci.SshNet.IntegrationTests/Dockerfile . --progress=plain
- docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v artifacts:/src/test/Renci.SshNet.IntegrationTests/artifacts -t sshtest
- ls artifacts
  
