os: Ubuntu2204

services:
- docker

#for testing purposes only
build_script:
  - dotnet build test/Renci.SshNet.IntegrationTests/ -c Debug

test_script:
- mkdir artifacts
- sudo tcpdump -i any -c1000 -w artifacts/tcpdump.pcap -v &
- dotnet test -c Debug --no-restore --no-build --results-directory artifacts --logger "console;verbosity=detailed" --logger "liquid.md;LogFileName=TestReport.md" -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput=artifacts/coverage.xml test/Renci.SshNet.IntegrationTests/Renci.SshNet.IntegrationTests.csproj
- ls artifacts
  
artifacts:
  - path: artifacts
    name: artifacts
